"""
Service for FinalTest business logic and CRUD operations.
Auto-generated by scaffold tool - extends EnhancedBaseService.
"""
from typing import List, Dict, Any, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.models.final_test import Finaltest
from app.services.enhanced_base_service import EnhancedBaseService
from app.db.schemas.final_test import FinaltestRead, FinaltestCreate, FinaltestUpdate
from loguru import logger

class FinaltestService(EnhancedBaseService[Finaltest]):
    """
    Service class for FinalTest operations.
    Inherits enhanced CRUD methods with parallel processing support.
    """
    
    def __init__(self):
        super().__init__(Finaltest)
    
    async def create_final_test(
        self, 
        db: AsyncSession, 
        final_test_data: FinaltestCreate
    ) -> FinaltestRead:
        """Create a new FinalTest"""
        try:
            final_test = await self.add(db, final_test_data.dict())
            return FinaltestRead.from_orm(final_test)
        except Exception as e:
            logger.error(f"Error creating final_test: {e}")
            raise
    
    async def get_final_test_by_id(
        self, 
        db: AsyncSession, 
        final_test_id: int
    ) -> Optional[FinaltestRead]:
        """Get FinalTest by ID"""
        final_test = await self.find_by_id(db, final_test_id)
        if final_test:
            return FinaltestRead.from_orm(final_test)
        return None
    
    async def update_final_test(
        self, 
        db: AsyncSession, 
        final_test_id: int,
        final_test_data: FinaltestUpdate
    ) -> Optional[FinaltestRead]:
        """Update FinalTest"""
        try:
            final_test = await self.find_by_id(db, final_test_id)
            if not final_test:
                return None
            
            update_data = {k: v for k, v in final_test_data.dict().items() if v is not None}
            updated_final_test = await self.update(db, final_test, update_data)
            return FinaltestRead.from_orm(updated_final_test)
        except Exception as e:
            logger.error(f"Error updating final_test: {e}")
            raise
    
    async def delete_final_test(self, db: AsyncSession, final_test_id: int) -> bool:
        """Delete FinalTest"""
        try:
            final_test = await self.find_by_id(db, final_test_id)
            if not final_test:
                return False
            
            await self.delete(db, final_test)
            return True
        except Exception as e:
            logger.error(f"Error deleting final_test: {e}")
            raise
    
    async def list_final_tests(
        self, 
        db: AsyncSession,
        skip: int = 0,
        limit: int = 100
    ) -> List[FinaltestRead]:
        """List FinalTests with pagination"""
        final_tests = await self.paginate(db, page=skip//limit + 1, page_size=limit)
        return [FinaltestRead.from_orm(final_test) for final_test in final_tests]
    
    # Enhanced parallel processing methods
    
    async def bulk_create_final_tests_parallel(
        self, 
        db: AsyncSession, 
        final_tests_data: List[FinaltestCreate],
        batch_size: Optional[int] = 50
    ) -> List[FinaltestRead]:
        """Create multiple FinalTests in parallel"""
        data_dicts = [final_test_data.dict() for final_test_data in final_tests_data]
        created_final_tests = await self.bulk_create_parallel(db, data_dicts, batch_size)
        return [FinaltestRead.from_orm(final_test) for final_test in created_final_tests]
    
    async def search_final_tests_parallel(
        self, 
        db: AsyncSession, 
        search_queries: List[Dict[str, Any]]
    ) -> List[List[FinaltestRead]]:
        """Search FinalTests in parallel"""
        results = await self.search_parallel(db, search_queries)
        return [[FinaltestRead.from_orm(final_test) for final_test in result] for result in results]
