"""TestItem Plugin - Modular Architecture.

This plugin provides CRUD operations, search, and additional features for TestItem management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import TestItem
from .routes import TestItemRoutes
from .schemas import (
    TestItemCreate,
    TestItemList,
    TestItemResponse,
    TestItemSearch,
    TestItemUpdate,
)
from .services import TestItemService

# Plugin metadata
PLUGIN_METADATA = {
    "name": "test_item_plugin",
    "version": "1.0.0",
    "description": "TestItem management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "bulk"],
    "models": ["TestItem"],
    "dependencies": [],
}

# Plugin exports
__all__ = [
    # Metadata
    "PLUGIN_METADATA",
    # Models
    "TestItem",
    # Schemas
    "TestItemCreate",
    "TestItemList",
    "TestItemResponse",
    # Routes
    "TestItemRoutes",
    "TestItemSearch",
    # Services
    "TestItemService",
    "TestItemUpdate",
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    "models": [TestItem],
    "services": {TestItemService},
    "routes": TestItemRoutes,
    "metadata": PLUGIN_METADATA,
}


def get_plugin_info():
    """Get plugin information."""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration."""
    return PLUGIN_COMPONENTS


def initialize_plugin() -> bool:
    """Initialize plugin components."""
    return True


# Plugin entry point
def register_plugin(app, context) -> bool | None:
    """Register plugin with the application."""
    try:
        # Register routes
        routes = TestItemRoutes()
        app.include_router(routes.get_router(), prefix="/api/v1", tags=["TestItem"])

        # Register services with context (not plugin_manager)
        service = TestItemService()
        context.register_service("test_item", service)

        # Register tasks if available
        # No tasks to register

        return True

    except Exception:
        return False
