"""
TestItem Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for TestItem management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import TestItem
from .schemas import (
    TestItemCreate,
    TestItemUpdate, 
    TestItemResponse,
    TestItemList,
    TestItemSearch
)
from .services import TestItemService
from .routes import TestItemRoutes


# Plugin metadata
PLUGIN_METADATA = {
    "name": "test_item_plugin",
    "version": "1.0.0",
    "description": "TestItem management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "bulk"],
    "models": ["TestItem"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "TestItem",
    
    # Schemas
    "TestItemCreate",
    "TestItemUpdate", 
    "TestItemResponse",
    "TestItemList",
    "TestItemSearch",
    
    # Services
    "TestItemService",
    
    # Routes
    "TestItemRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [TestItem],
    'services': {TestItemService},
    'routes': TestItemRoutes,
    'metadata': PLUGIN_METADATA,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing TestItem Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = TestItemRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["TestItem"]
        )
        
        # Register services with context (not plugin_manager)
        service = TestItemService()
        context.register_service("test_item", service)
        
        # Register tasks if available
        # No tasks to register
        
        print(f"✅ TestItem plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register TestItem plugin: {e}")
        return False
