"""
Smart Migration: drop_column
Table: testitems
Zero Downtime: True
Estimated Duration: < 1 minute
Rollback Strategy: Restore column from backup or re-add with default values

Risks:
- Data loss for the dropped column
- Application errors if column is still used
- Potential impact on existing queries

Prerequisites:
- Create database backup
- Verify no active references to dropped objects
- Notify stakeholders of data removal
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_testitem_drop_column

Revision ID: 2f767bed0dd7
Revises: 872e58f64b4c
Create Date: 2025-06-03 12:46:56.399481

"""

# Zero-downtime column removal strategy
# 1. Stop using column in application code
# 2. Deploy application without column references
# 3. Drop column in separate migration

def upgrade_zero_downtime():
    """Zero-downtime downgrade strategy for column removal"""
    # Step 1: Mark column as deprecated (add comment)
    # op.execute("COMMENT ON COLUMN table_name.old_column IS 'DEPRECATED - scheduled for removal'")
    
    # Step 2: In subsequent migration, drop the column
    # op.drop_column('table_name', 'old_column')
    
    pass  # Actual drop should be in separate migration

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2f767bed0dd7'
down_revision: Union[str, None] = '872e58f64b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_items', 'price')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
