"""Add organizations and multi-tenancy support

Revision ID: 4231a548294e
Revises: 6aa199c2e923
Create Date: 2025-06-01 23:33:25.549614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4231a548294e'
down_revision: Union[str, None] = '6aa199c2e923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
