"""
Smart Migration: add_column
Table: producttests
Zero Downtime: True
Estimated Duration: < 2 minutes
Rollback Strategy: Drop the newly added column

Risks:

Prerequisites:
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_add_column

Revision ID: 77d6a6f9cafc
Revises: b4bb130dfdd5
Create Date: 2025-06-03 13:16:26.273067

"""

# Zero-downtime column addition strategy
# 1. Add column as nullable
# 2. Populate with default values
# 3. Make non-null if required (in separate migration)

def upgrade_zero_downtime():
    """Zero-downtime upgrade strategy"""
    # Step 1: Add nullable column
    op.add_column('table_name', sa.Column('new_column', sa.String(), nullable=True))
    
    # Step 2: Populate with default values (if needed)
    # op.execute("UPDATE table_name SET new_column = 'default_value' WHERE new_column IS NULL")
    
    # Step 3: Add constraints (in separate migration if needed)
    # op.alter_column('table_name', 'new_column', nullable=False)

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '77d6a6f9cafc'
down_revision: Union[str, None] = 'b4bb130dfdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tests_id'), 'product_tests', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tests_id'), table_name='product_tests')
    op.drop_table('product_tests')
    # ### end Alembic commands ###
