"""Add Product2 model

Revision ID: 7e9b2a5e4614
Revises: d3b4eb3cc676
Create Date: 2025-06-02 02:28:19.357360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e9b2a5e4614'
down_revision: Union[str, None] = 'd3b4eb3cc676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product2s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.Column('updated_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product2s_id'), 'product2s', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product2s_id'), table_name='product2s')
    op.drop_table('product2s')
    # ### end Alembic commands ###
