"""add_status_column_to_test_items

Revision ID: b9ea75929f1d
Revises: 570384ec46ec
Create Date: 2025-06-03 12:11:10.656059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9ea75929f1d'
down_revision: Union[str, None] = '570384ec46ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_items', 'status')
    # ### end Alembic commands ###
