"""
Smart Migration: rename_column
Table: testitems
Zero Downtime: True
Estimated Duration: 5-15 minutes (multi-step process)
Rollback Strategy: Rename column back to original name

Risks:
- Application compatibility issues
- Temporary data duplication
- Complex rollback process

Prerequisites:
- Update application code to handle both column names
- Coordinate with development team
- Plan multi-step deployment
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_testitem_rename_column

Revision ID: bae354ea12ad
Revises: 417e3343e93d
Create Date: 2025-06-03 12:57:56.583128

"""

# Zero-downtime column rename strategy
# 1. Add new column
# 2. Copy data from old to new
# 3. Update application to use new column
# 4. Drop old column

def upgrade_zero_downtime():
    """Zero-downtime column rename strategy"""
    # Step 1: Add new column
    op.add_column('table_name', sa.Column('new_column_name', sa.String(), nullable=True))
    
    # Step 2: Copy data
    op.execute("UPDATE table_name SET new_column_name = old_column_name")
    
    # Step 3: Make new column not null if needed
    # op.alter_column('table_name', 'new_column_name', nullable=False)
    
    # Step 4: Drop old column (in separate migration after app deployment)
    # op.drop_column('table_name', 'old_column_name')

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bae354ea12ad'
down_revision: Union[str, None] = '417e3343e93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('item_status', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_items_id'), 'test_items', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_items_id'), table_name='test_items')
    op.drop_table('test_items')
    # ### end Alembic commands ###
