"""add_security_models

Revision ID: bbeffc275826
Revises: 95a505110f17
Create Date: 2025-06-06 02:36:57.370977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bbeffc275826'
down_revision: Union[str, None] = '95a505110f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('product_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_name', 'product_tests', ['name'], unique=True)
    op.create_index(op.f('ix_product_tests_id'), 'product_tests', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tests_id'), table_name='product_tests')
    op.drop_index('idx_name', table_name='product_tests')
    op.drop_table('product_tests')
    # ### end Alembic commands ###
