"""
Smart Migration: modify_column
Table: producttests
Zero Downtime: True
Estimated Duration: 2-5 minutes
Rollback Strategy: Revert column to original type and constraints

Risks:
- Data conversion errors
- Performance impact during conversion
- Possible data truncation

Prerequisites:
- Test data conversion on sample dataset
- Verify application compatibility
- Plan for potential data cleanup
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_modify_column

Revision ID: e32b166ceb0c
Revises: fd1b27d6e68e
Create Date: 2025-06-03 13:18:33.553026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e32b166ceb0c'
down_revision: Union[str, None] = 'fd1b27d6e68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tests_id'), 'product_tests', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tests_id'), table_name='product_tests')
    op.drop_table('product_tests')
    # ### end Alembic commands ###
