[project]
name = "fastapi-postgres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "uvicorn[standard]",
    "sqlalchemy",
    "asyncpg",
    "psycopg2-binary",
    "python-dotenv",
    "pydantic",
    "httpx",
    "jinja2",
    "python-multipart",
    "email-validator",
    "itsdangerous",
    "pydantic-settings",
    "greenlet",
    "fastapi-mcp>=0.3.3",
    "loguru>=0.7.3",
    "alembic",
    "pyjwt",
    "passlib[bcrypt]",
    "fastmcp>=2.3.2",
    "mcp>=1.8.0",
]
[tool.poetry.dependencies]
python = "^3.11"
fastapi = ">=0.100,<1.0.0"
pydantic = ">=2.0,<3.0.0"
fastapi-mcp = "^0.3.3"
mcp = "^1.8.0"
