"""
Order Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for Order management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import Order
from .schemas import (
    OrderCreate,
    OrderUpdate, 
    OrderResponse,
    OrderList,
    OrderSearch
)
from .services import OrderService
from .routes import OrderRoutes
from .tasks import TASKS

# Plugin metadata
PLUGIN_METADATA = {
    "name": "order_plugin",
    "version": "1.0.0",
    "description": "Order management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "tasks", "bulk"],
    "models": ["Order"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "Order",
    
    # Schemas
    "OrderCreate",
    "OrderUpdate", 
    "OrderResponse",
    "OrderList",
    "OrderSearch",
    
    # Services
    "OrderService",
    
    # Routes
    "OrderRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [Order],
    'services': {OrderService},
    'routes': OrderRoutes,
    'metadata': PLUGIN_METADATA,    'tasks': TASKS,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing Order Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = OrderRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["Order"]
        )
        
        # Register services with context (not plugin_manager)
        service = OrderService()
        context.register_service("order", service)
        
        # Register tasks if available
        if hasattr(OrderRoutes, 'TASKS'):
            for task_name, task_func in TASKS.items():
                context.register_task(task_name, task_func)
        
        print(f"✅ Order plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register Order plugin: {e}")
        return False
