"""
ShoppingCart Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for ShoppingCart management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import ShoppingCart
from .schemas import (
    ShoppingCartCreate,
    ShoppingCartUpdate, 
    ShoppingCartResponse,
    ShoppingCartList,
    ShoppingCartSearch
)
from .services import ShoppingCartService
from .routes import ShoppingCartRoutes
from .tasks import TASKS

# Plugin metadata
PLUGIN_METADATA = {
    "name": "shopping_cart_plugin",
    "version": "1.0.0",
    "description": "ShoppingCart management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "tasks", "bulk"],
    "models": ["ShoppingCart"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "ShoppingCart",
    
    # Schemas
    "ShoppingCartCreate",
    "ShoppingCartUpdate", 
    "ShoppingCartResponse",
    "ShoppingCartList",
    "ShoppingCartSearch",
    
    # Services
    "ShoppingCartService",
    
    # Routes
    "ShoppingCartRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [ShoppingCart],
    'services': {ShoppingCartService},
    'routes': ShoppingCartRoutes,
    'metadata': PLUGIN_METADATA,    'tasks': TASKS,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing ShoppingCart Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = ShoppingCartRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["ShoppingCart"]
        )
        
        # Register services with context (not plugin_manager)
        service = ShoppingCartService()
        context.register_service("shopping_cart", service)
        
        # Register tasks if available
        if hasattr(ShoppingCartRoutes, 'TASKS'):
            for task_name, task_func in TASKS.items():
                context.register_task(task_name, task_func)
        
        print(f"✅ ShoppingCart plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register ShoppingCart plugin: {e}")
        return False
