"""add_shoppingcart_model

Revision ID: 23685970d345
Revises: 1ea28bdf5e5a
Create Date: 2025-06-11 23:47:14.341007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23685970d345'
down_revision: Union[str, None] = '1ea28bdf5e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_carts_id'), table_name='shopping_carts')
    op.drop_table('shopping_carts')
    # ### end Alembic commands ###

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
