"""Remove tag2

Revision ID: 3d8b1889c95a
Revises: 8b4456e98a9a
Create Date: 2025-05-11 00:24:16.689677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8b1889c95a'
down_revision: Union[str, None] = '8b4456e98a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_tag2s_id', table_name='tag2s')
    op.drop_table('tag2s')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag2s',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tagname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tag2s_pkey')
    )
    op.create_index('ix_tag2s_id', 'tag2s', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey')
    )
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
