"""
Smart Migration: add_column
Table: testitems
Zero Downtime: True
Estimated Duration: < 2 minutes
Rollback Strategy: Drop the newly added column

Risks:


Prerequisites:
- Test migration on staging environment
- Prepare rollback plan
"""

"""smart_migration_testitem_add_column

Revision ID: 570384ec46ec
Revises: 6b6010b74f18
Create Date: 2025-06-03 12:03:06.730282

"""

# Zero-downtime column addition strategy
# 1. Add column as nullable
# 2. Populate with default values
# 3. Make non-null if required (in separate migration)

def upgrade_zero_downtime():
    """Zero-downtime upgrade strategy"""
    # Step 1: Add nullable column
    op.add_column('table_name', sa.Column('new_column', sa.String(), nullable=True))
    
    # Step 2: Populate with default values (if needed)
    # op.execute("UPDATE table_name SET new_column = 'default_value' WHERE new_column IS NULL")
    
    # Step 3: Add constraints (in separate migration if needed)
    # op.alter_column('table_name', 'new_column', nullable=False)


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570384ec46ec'
down_revision: Union[str, None] = '6b6010b74f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
