"""Add tag2

Revision ID: 8b4456e98a9a
Revises: 76dc09ce562b
Create Date: 2025-05-11 00:22:11.804814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4456e98a9a'
down_revision: Union[str, None] = '76dc09ce562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag2s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag2s_id'), 'tag2s', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag2s_id'), table_name='tag2s')
    op.drop_table('tag2s')
    # ### end Alembic commands ###
