"""
Smart Migration: add_constraint
Table: producttests
Zero Downtime: True
Estimated Duration: 1-5 minutes
Rollback Strategy: Drop the newly added constraint

Risks:
- Constraint validation on existing data
- Potential data quality issues
- Performance impact during validation

Prerequisites:
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_add_constraint

Revision ID: 95a505110f17
Revises: a09d5ff102b7
Create Date: 2025-06-03 13:32:18.638765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a505110f17'
down_revision: Union[str, None] = 'a09d5ff102b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_name', table_name='product_tests')
    op.drop_index('ix_product_tests_id', table_name='product_tests')
    op.drop_table('product_tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('product_rating', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_tests_pkey')
    )
    op.create_index('ix_product_tests_id', 'product_tests', ['id'], unique=False)
    op.create_index('idx_name', 'product_tests', ['name'], unique=True)
    # ### end Alembic commands ###
