"""
Smart Migration: add_index
Table: producttests
Zero Downtime: True
Estimated Duration: 2-10 minutes (depends on table size)
Rollback Strategy: Drop the newly created index

Risks:
- Table locking during index creation
- Increased storage requirements
- Performance impact during creation

Prerequisites:
- Ensure sufficient disk space
- Schedule during low-traffic period
- Monitor system resources
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_add_index

Revision ID: a09d5ff102b7
Revises: 114d478445f8
Create Date: 2025-06-03 13:31:31.768444

"""

# Zero-downtime index creation strategy
# Use CONCURRENTLY option for PostgreSQL

def upgrade_zero_downtime():
    """Zero-downtime index creation"""
    # PostgreSQL: Create index concurrently
    op.execute("CREATE INDEX CONCURRENTLY idx_table_column ON table_name (column_name)")
    
    # For other databases, create index normally (small downtime)
    # op.create_index('idx_table_column', 'table_name', ['column_name'])


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09d5ff102b7'
down_revision: Union[str, None] = '114d478445f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_name', 'product_tests', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_name', table_name='product_tests')
    # ### end Alembic commands ###
