"""
Smart Migration: modify_column
Table: producttests
Zero Downtime: True
Estimated Duration: 2-5 minutes
Rollback Strategy: Revert column to original type and constraints

Risks:
- Data conversion errors
- Performance impact during conversion
- Possible data truncation

Prerequisites:
- Test data conversion on sample dataset
- Verify application compatibility
- Plan for potential data cleanup
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_modify_column

Revision ID: b4bb130dfdd5
Revises: 674f2d6102e5
Create Date: 2025-06-03 13:14:58.499899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4bb130dfdd5'
down_revision: Union[str, None] = '674f2d6102e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_tests_id', table_name='product_tests')
    op.drop_table('product_tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_tests_pkey')
    )
    op.create_index('ix_product_tests_id', 'product_tests', ['id'], unique=False)
    # ### end Alembic commands ###
