"""
Smart Migration: add_column
Table: testitems
Zero Downtime: True
Estimated Duration: < 2 minutes
Rollback Strategy: Drop the newly added column

Risks:


Prerequisites:
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_testitem_add_column

Revision ID: cdc35aa671a7
Revises: 2f767bed0dd7
Create Date: 2025-06-03 12:50:34.318698

"""

# Zero-downtime column addition strategy
# 1. Add column as nullable
# 2. Populate with default values
# 3. Make non-null if required (in separate migration)

def upgrade_zero_downtime():
    """Zero-downtime upgrade strategy"""
    # Step 1: Add nullable column
    op.add_column('table_name', sa.Column('new_column', sa.String(), nullable=True))
    
    # Step 2: Populate with default values (if needed)
    # op.execute("UPDATE table_name SET new_column = 'default_value' WHERE new_column IS NULL")
    
    # Step 3: Add constraints (in separate migration if needed)
    # op.alter_column('table_name', 'new_column', nullable=False)


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdc35aa671a7'
down_revision: Union[str, None] = '2f767bed0dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_items_id', table_name='test_items')
    op.drop_table('test_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_items_pkey')
    )
    op.create_index('ix_test_items_id', 'test_items', ['id'], unique=False)
    # ### end Alembic commands ###
