"""
Smart Migration: rename_column
Table: producttests
Zero Downtime: True
Estimated Duration: 5-15 minutes (multi-step process)
Rollback Strategy: Rename column back to original name

Risks:
- Application compatibility issues
- Temporary data duplication
- Complex rollback process

Prerequisites:
- Update application code to handle both column names
- Coordinate with development team
- Plan multi-step deployment
- Test migration on staging environment
- Prepare rollback plan
- Coordinate with operations team
"""

"""smart_migration_producttest_rename_column

Revision ID: d3cd9cccd1ec
Revises: e32b166ceb0c
Create Date: 2025-06-03 13:19:01.086774

"""

# Zero-downtime column rename strategy
# 1. Add new column
# 2. Copy data from old to new
# 3. Update application to use new column
# 4. Drop old column

def upgrade_zero_downtime():
    """Zero-downtime column rename strategy"""
    # Step 1: Add new column
    op.add_column('table_name', sa.Column('new_column_name', sa.String(), nullable=True))
    
    # Step 2: Copy data
    op.execute("UPDATE table_name SET new_column_name = old_column_name")
    
    # Step 3: Make new column not null if needed
    # op.alter_column('table_name', 'new_column_name', nullable=False)
    
    # Step 4: Drop old column (in separate migration after app deployment)
    # op.drop_column('table_name', 'old_column_name')


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd9cccd1ec'
down_revision: Union[str, None] = 'e32b166ceb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tests', sa.Column('product_rating', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('product_tests', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tests', sa.Column('rating', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('product_tests', 'product_rating')
    # ### end Alembic commands ###
