"""add_testremoval3_model

Revision ID: ec62d2a648e7
Revises: 0002d43c0ee3
Create Date: 2025-06-15 17:03:42.622527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec62d2a648e7'
down_revision: Union[str, None] = '0002d43c0ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_removal3s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_removal3s_id'), 'test_removal3s', ['id'], unique=False)

    op.drop_index('ix_test_removals_id', table_name='test_removals')
    op.drop_table('test_removals')

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_removal3s_id'), table_name='test_removal3s')
    op.drop_table('test_removal3s')
    # ### end Alembic commands ###
