"""
Product Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for Product management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import Product
from .schemas import (
    ProductCreate,
    ProductUpdate, 
    ProductResponse,
    ProductList,
    ProductSearch
)
from .services import ProductService
from .routes import ProductRoutes
from .tasks import TASKS

# Plugin metadata
PLUGIN_METADATA = {
    "name": "product_plugin",
    "version": "1.0.0",
    "description": "Product management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "tasks", "bulk"],
    "models": ["Product"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "Product",
    
    # Schemas
    "ProductCreate",
    "ProductUpdate", 
    "ProductResponse",
    "ProductList",
    "ProductSearch",
    
    # Services
    "ProductService",
    
    # Routes
    "ProductRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [Product],
    'services': {ProductService},
    'routes': ProductRoutes,
    'metadata': PLUGIN_METADATA,    'tasks': TASKS,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing Product Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = ProductRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["Product"]
        )
        
        # Register services with context (not plugin_manager)
        service = ProductService()
        context.register_service("product", service)
        
        # Register tasks if available
        if hasattr(ProductRoutes, 'TASKS'):
            for task_name, task_func in TASKS.items():
                context.register_task(task_name, task_func)
        
        print(f"✅ Product plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register Product plugin: {e}")
        return False
