"""
Custom Pydantic BaseModel with enhanced features.
Generated by enhanced scaffold tool.
"""
from datetime import datetime
from typing import Any, Dict
from zoneinfo import ZoneInfo

from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, ConfigDict


def datetime_to_gmt_str(dt: datetime) -> str:
    """Convert datetime to GMT string format"""
    if not dt.tzinfo:
        dt = dt.replace(tzinfo=ZoneInfo("UTC"))
    return dt.strftime("%Y-%m-%dT%H:%M:%S%z")


class CustomBaseModel(BaseModel):
    """
    Custom base model with enhanced serialization and configuration.
    All model schemas should inherit from this class.
    """
    
    model_config = ConfigDict(
        json_encoders={datetime: datetime_to_gmt_str},
        populate_by_name=True,
        validate_assignment=True,
        arbitrary_types_allowed=True,
        str_strip_whitespace=True
    )
    
    def serializable_dict(self, **kwargs) -> Dict[str, Any]:
        """Return a dict which contains only serializable fields"""
        default_dict = self.model_dump()
        return jsonable_encoder(default_dict)
    
    def to_dict(self, exclude_none: bool = True) -> Dict[str, Any]:
        """Convert to dictionary with options"""
        return self.model_dump(exclude_none=exclude_none)
    
    class Config:
        """Pydantic configuration"""
        from_attributes = True
        use_enum_values = True
        validate_assignment = True
        arbitrary_types_allowed = True 