"""Custom exceptions for FinalTest.
Auto-generated by enhanced scaffold tool.
"""

from fastapi import HTTPException, status


class FinaltestException(HTTPException):
    """Base exception for FinalTest operations."""



class FinaltestNotFound(FinaltestException):
    """Exception raised when FinalTest is not found."""

    def __init__(self, detail: str = "FinalTest not found") -> None:
        super().__init__(status_code=status.HTTP_404_NOT_FOUND, detail=detail)


class FinaltestAlreadyExists(FinaltestException):
    """Exception raised when FinalTest already exists."""

    def __init__(self, detail: str = "FinalTest already exists") -> None:
        super().__init__(status_code=status.HTTP_409_CONFLICT, detail=detail)


class FinaltestValidationError(FinaltestException):
    """Exception raised when FinalTest validation fails."""

    def __init__(self, detail: str = "Validation error") -> None:
        super().__init__(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=detail,
        )


class FinaltestPermissionDenied(FinaltestException):
    """Exception raised when user lacks permission."""

    def __init__(self, detail: str = "Permission denied") -> None:
        super().__init__(status_code=status.HTTP_403_FORBIDDEN, detail=detail)


class FinaltestBusinessLogicError(FinaltestException):
    """Exception raised when business logic validation fails."""

    def __init__(self, detail: str = "Business logic error") -> None:
        super().__init__(status_code=status.HTTP_400_BAD_REQUEST, detail=detail)
