"""
Customer Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for Customer management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import Customer
from .schemas import (
    CustomerCreate,
    CustomerUpdate, 
    CustomerResponse,
    CustomerList,
    CustomerSearch
)
from .services import CustomerService
from .routes import CustomerRoutes


# Plugin metadata
PLUGIN_METADATA = {
    "name": "customer_plugin",
    "version": "1.0.0",
    "description": "Customer management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search"],
    "models": ["Customer"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "Customer",
    
    # Schemas
    "CustomerCreate",
    "CustomerUpdate", 
    "CustomerResponse",
    "CustomerList",
    "CustomerSearch",
    
    # Services
    "CustomerService",
    
    # Routes
    "CustomerRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [Customer],
    'services': {CustomerService},
    'routes': CustomerRoutes,
    'metadata': PLUGIN_METADATA,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing Customer Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = CustomerRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["Customer"]
        )
        
        # Register services with context (not plugin_manager)
        service = CustomerService()
        context.register_service("customer", service)
        
        # Register tasks if available
        # No tasks to register
        
        print(f"✅ Customer plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register Customer plugin: {e}")
        return False
