"""
TestCleanup Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for TestCleanup management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import TestCleanup
from .schemas import (
    TestCleanupCreate,
    TestCleanupUpdate, 
    TestCleanupResponse,
    TestCleanupList,
    TestCleanupSearch
)
from .services import TestCleanupService
from .routes import TestCleanupRoutes


# Plugin metadata
PLUGIN_METADATA = {
    "name": "test_cleanup_plugin",
    "version": "1.0.0",
    "description": "TestCleanup management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search"],
    "models": ["TestCleanup"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "TestCleanup",
    
    # Schemas
    "TestCleanupCreate",
    "TestCleanupUpdate", 
    "TestCleanupResponse",
    "TestCleanupList",
    "TestCleanupSearch",
    
    # Services
    "TestCleanupService",
    
    # Routes
    "TestCleanupRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [TestCleanup],
    'services': {TestCleanupService},
    'routes': TestCleanupRoutes,
    'metadata': PLUGIN_METADATA,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing TestCleanup Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = TestCleanupRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["TestCleanup"]
        )
        
        # Register services with context (not plugin_manager)
        service = TestCleanupService()
        context.register_service("test_cleanup", service)
        
        # Register tasks if available
        # No tasks to register
        
        print(f"✅ TestCleanup plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register TestCleanup plugin: {e}")
        return False
