"""ProductTest Plugin - Modular Architecture.

This plugin provides CRUD operations, search, and additional features for ProductTest management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import ProductTest
from .routes import ProductTestRoutes
from .schemas import (
    ProductTestCreate,
    ProductTestList,
    ProductTestResponse,
    ProductTestSearch,
    ProductTestUpdate,
)
from .services import ProductTestService

# Plugin metadata
PLUGIN_METADATA = {
    "name": "product_test_plugin",
    "version": "1.0.0",
    "description": "ProductTest management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search"],
    "models": ["ProductTest"],
    "dependencies": [],
}

# Plugin exports
__all__ = [
    # Metadata
    "PLUGIN_METADATA",
    # Models
    "ProductTest",
    # Schemas
    "ProductTestCreate",
    "ProductTestList",
    "ProductTestResponse",
    # Routes
    "ProductTestRoutes",
    "ProductTestSearch",
    # Services
    "ProductTestService",
    "ProductTestUpdate",
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    "models": [ProductTest],
    "services": {ProductTestService},
    "routes": ProductTestRoutes,
    "metadata": PLUGIN_METADATA,
}


def get_plugin_info():
    """Get plugin information."""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration."""
    return PLUGIN_COMPONENTS


def initialize_plugin() -> bool:
    """Initialize plugin components."""
    return True


# Plugin entry point
def register_plugin(app, context) -> bool | None:
    """Register plugin with the application."""
    try:
        # Register routes
        routes = ProductTestRoutes()
        app.include_router(routes.get_router(), prefix="/api/v1", tags=["ProductTest"])

        # Register services with context (not plugin_manager)
        service = ProductTestService()
        context.register_service("product_test", service)

        # Register tasks if available
        # No tasks to register

        return True

    except Exception:
        return False
