"""
Plugin __init__.py template generator
"""
from typing import List, Dict, Any
import re


class InitTemplate:
    """Generates plugin __init__.py templates"""
    
    def generate(self, model_name: str, with_tasks: bool = False, with_bulk: bool = False) -> str:
        """Generate plugin __init__.py file content"""
        snake_name = re.sub(r'(?<!^)(?=[A-Z])', '_', model_name).lower()
        pascal_name = model_name
        
        # Build features list
        features = ["crud", "search"]
        if with_tasks:
            features.append("tasks")
        if with_bulk:
            features.append("bulk")
        
        features_str = ', '.join([f'"{f}"' for f in features])
        
        tasks_import = ""
        tasks_export = ""
        if with_tasks:
            tasks_import = "from .tasks import TASKS"
            tasks_export = "    'tasks': TASKS,"
        
        template = f'''"""
{pascal_name} Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for {pascal_name} management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import {pascal_name}
from .schemas import (
    {pascal_name}Create,
    {pascal_name}Update, 
    {pascal_name}Response,
    {pascal_name}List,
    {pascal_name}Search
)
from .services import {pascal_name}Service
from .routes import {pascal_name}Routes
{tasks_import}

# Plugin metadata
PLUGIN_METADATA = {{
    "name": "{snake_name}_plugin",
    "version": "1.0.0",
    "description": "{pascal_name} management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": [{features_str}],
    "models": ["{pascal_name}"],
    "dependencies": []
}}

# Plugin exports
__all__ = [
    # Models
    "{pascal_name}",
    
    # Schemas
    "{pascal_name}Create",
    "{pascal_name}Update", 
    "{pascal_name}Response",
    "{pascal_name}List",
    "{pascal_name}Search",
    
    # Services
    "{pascal_name}Service",
    
    # Routes
    "{pascal_name}Routes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {{
    'models': [{pascal_name}],
    'services': {{{pascal_name}Service}},
    'routes': {pascal_name}Routes,
    'metadata': PLUGIN_METADATA,{tasks_export}
}}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing {pascal_name} Plugin v{{PLUGIN_METADATA['version']}}")
    print(f"📋 Features: {{', '.join(PLUGIN_METADATA['features'])}}")
    return True


# Plugin entry point
def register_plugin(app, plugin_manager):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = {pascal_name}Routes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["{pascal_name}"]
        )
        
        # Register services
        service = {pascal_name}Service()
        plugin_manager.register_service("{snake_name}", service)
        
        # Register tasks if available
        {f'''if hasattr({pascal_name}Routes, 'TASKS'):
            for task_name, task_func in TASKS.items():
                plugin_manager.register_task(task_name, task_func)''' if with_tasks else '# No tasks to register'}
        
        print(f"✅ {pascal_name} plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register {pascal_name} plugin: {{e}}")
        return False
'''
        
        return template 