"""
Book Plugin - Modular Architecture

This plugin provides CRUD operations, search, and additional features for Book management.
Generated by FastAPI Scaffold Generator v4.0
"""

from .models import Book
from .schemas import (
    BookCreate,
    BookUpdate, 
    BookResponse,
    BookList,
    BookSearch
)
from .services import BookService
from .routes import BookRoutes
from .tasks import TASKS

# Plugin metadata
PLUGIN_METADATA = {
    "name": "book_plugin",
    "version": "1.0.0",
    "description": "Book management plugin with modular architecture",
    "author": "FastAPI Scaffold Generator v4.0",
    "features": ["crud", "search", "tasks"],
    "models": ["Book"],
    "dependencies": []
}

# Plugin exports
__all__ = [
    # Models
    "Book",
    
    # Schemas
    "BookCreate",
    "BookUpdate", 
    "BookResponse",
    "BookList",
    "BookSearch",
    
    # Services
    "BookService",
    
    # Routes
    "BookRoutes",
    
    # Metadata
    "PLUGIN_METADATA"
]

# Plugin components for registration
PLUGIN_COMPONENTS = {
    'models': [Book],
    'services': {BookService},
    'routes': BookRoutes,
    'metadata': PLUGIN_METADATA,    'tasks': TASKS,
}


def get_plugin_info():
    """Get plugin information"""
    return PLUGIN_METADATA


def get_plugin_components():
    """Get plugin components for registration"""
    return PLUGIN_COMPONENTS


def initialize_plugin():
    """Initialize plugin components"""
    print(f"🚀 Initializing Book Plugin v{PLUGIN_METADATA['version']}")
    print(f"📋 Features: {', '.join(PLUGIN_METADATA['features'])}")
    return True


# Plugin entry point
def register_plugin(app, context):
    """Register plugin with the application"""
    try:
        # Register routes
        routes = BookRoutes()
        app.include_router(
            routes.get_router(),
            prefix="/api/v1",
            tags=["Book"]
        )
        
        # Register services with context (not plugin_manager)
        service = BookService()
        context.register_service("book", service)
        
        # Register tasks if available
        if hasattr(BookRoutes, 'TASKS'):
            for task_name, task_func in TASKS.items():
                context.register_task(task_name, task_func)
        
        print(f"✅ Book plugin registered successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to register Book plugin: {e}")
        return False
