"""Alembic Management System.

This module provides comprehensive Alembic migration management,
including automatic migration generation, plugin model discovery,
and database state management.
"""

import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from alembic import command
from alembic.config import Config
from loguru import logger
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from app.core.config import get_settings
from app.db.base import Base

settings = get_settings()


class AlembicManager:
    """Manages Alembic migrations and database schema operations."""
    
    def __init__(self):
        self.settings = settings
        self.project_root = Path(__file__).parent.parent.parent
        self.alembic_cfg_path = self.project_root / "alembic.ini"
        self.alembic_dir = self.project_root / "alembic"
        self.versions_dir = self.alembic_dir / "versions"
        
    def get_alembic_config(self) -> Config:
        """Get Alembic configuration."""
        if not self.alembic_cfg_path.exists():
            raise FileNotFoundError(f"Alembic config not found: {self.alembic_cfg_path}")
            
        cfg = Config(str(self.alembic_cfg_path))
        
        # Set the database URL from settings
        db_url = self.settings.database_url_without_async
        if db_url:
            cfg.set_main_option("sqlalchemy.url", db_url)
            
        return cfg
    
    def check_alembic_setup(self) -> Dict[str, Any]:
        """Check if Alembic is properly set up."""
        status = {
            "alembic_ini_exists": self.alembic_cfg_path.exists(),
            "alembic_dir_exists": self.alembic_dir.exists(),
            "versions_dir_exists": self.versions_dir.exists(),
            "env_py_exists": (self.alembic_dir / "env.py").exists(),
            "database_url_configured": bool(self.settings.database_url_without_async),
            "current_revision": None,
            "pending_migrations": [],
            "total_migrations": 0,
        }
        
        try:
            cfg = self.get_alembic_config()
            
            # Get current revision
            from alembic.runtime.migration import MigrationContext
            engine = create_engine(self.settings.database_url_without_async)
            
            with engine.connect() as conn:
                context = MigrationContext.configure(conn)
                status["current_revision"] = context.get_current_revision()
                
            # Count migrations
            if self.versions_dir.exists():
                status["total_migrations"] = len(list(self.versions_dir.glob("*.py")))
                
        except Exception as e:
            logger.error(f"Error checking Alembic setup: {e}")
            status["error"] = str(e)
            
        return status
    
    def initialize_alembic(self) -> bool:
        """Initialize Alembic if not already set up."""
        try:
            if not self.alembic_dir.exists():
                logger.info("Initializing Alembic...")
                command.init(self.get_alembic_config(), str(self.alembic_dir))
                logger.info("✅ Alembic initialized successfully")
                return True
            else:
                logger.info("✅ Alembic already initialized")
                return True
        except Exception as e:
            logger.error(f"❌ Failed to initialize Alembic: {e}")
            return False
    
    def create_migration(
        self, 
        message: str, 
        autogenerate: bool = True,
        empty: bool = False
    ) -> Optional[str]:
        """Create a new migration."""
        try:
            cfg = self.get_alembic_config()
            
            if empty:
                # Create empty migration
                revision = command.revision(cfg, message=message)
            else:
                # Create autogenerated migration
                revision = command.revision(
                    cfg, 
                    message=message, 
                    autogenerate=autogenerate
                )
            
            logger.info(f"✅ Migration created: {message}")
            return revision.revision if revision else None
            
        except Exception as e:
            logger.error(f"❌ Failed to create migration: {e}")
            return None
    
    def run_migrations(self, revision: str = "head") -> bool:
        """Run migrations to specified revision."""
        try:
            cfg = self.get_alembic_config()
            command.upgrade(cfg, revision)
            logger.info(f"✅ Migrations applied to: {revision}")
            return True
        except Exception as e:
            logger.error(f"❌ Failed to run migrations: {e}")
            return False
    
    def downgrade_migrations(self, revision: str) -> bool:
        """Downgrade migrations to specified revision."""
        try:
            cfg = self.get_alembic_config()
            command.downgrade(cfg, revision)
            logger.info(f"✅ Migrations downgraded to: {revision}")
            return True
        except Exception as e:
            logger.error(f"❌ Failed to downgrade migrations: {e}")
            return False
    
    def get_migration_history(self) -> List[Dict[str, Any]]:
        """Get migration history."""
        try:
            cfg = self.get_alembic_config()
            
            # Get revision history
            from alembic.script import ScriptDirectory
            script_dir = ScriptDirectory.from_config(cfg)
            
            history = []
            for revision in script_dir.walk_revisions():
                history.append({
                    "revision": revision.revision,
                    "down_revision": revision.down_revision,
                    "description": revision.doc,
                    "branch_labels": revision.branch_labels,
                })
                
            return history
        except Exception as e:
            logger.error(f"Error getting migration history: {e}")
            return []
    
    def get_current_revision(self) -> Optional[str]:
        """Get current database revision."""
        try:
            engine = create_engine(self.settings.database_url_without_async)
            
            with engine.connect() as conn:
                from alembic.runtime.migration import MigrationContext
                context = MigrationContext.configure(conn)
                return context.get_current_revision()
                
        except Exception as e:
            logger.error(f"Error getting current revision: {e}")
            return None
    
    def check_for_pending_migrations(self) -> List[str]:
        """Check for pending migrations."""
        try:
            cfg = self.get_alembic_config()
            from alembic.script import ScriptDirectory
            
            script_dir = ScriptDirectory.from_config(cfg)
            current_rev = self.get_current_revision()
            
            if not current_rev:
                # No migrations applied yet
                return [rev.revision for rev in script_dir.walk_revisions()]
            
            # Get pending revisions
            pending = []
            for revision in script_dir.walk_revisions("head", current_rev):
                if revision.revision != current_rev:
                    pending.append(revision.revision)
                    
            return pending
            
        except Exception as e:
            logger.error(f"Error checking pending migrations: {e}")
            return []
    
    def reset_database(self) -> bool:
        """Reset database to clean state (DANGEROUS!)."""
        try:
            logger.warning("🚨 Resetting database - this will drop all tables!")
            
            engine = create_engine(self.settings.database_url_without_async)
            
            # Drop all tables
            Base.metadata.drop_all(engine)
            
            # Drop alembic version table
            with engine.connect() as conn:
                conn.execute(text("DROP TABLE IF EXISTS alembic_version CASCADE"))
                conn.commit()
            
            logger.info("✅ Database reset complete")
            return True
            
        except Exception as e:
            logger.error(f"❌ Failed to reset database: {e}")
            return False
    
    def create_fresh_migration(self, message: str = "Initial migration") -> bool:
        """Create a fresh migration after reset."""
        try:
            # First, create all tables
            engine = create_engine(self.settings.database_url_without_async)
            Base.metadata.create_all(engine)
            
            # Then stamp the database with head revision
            cfg = self.get_alembic_config()
            command.stamp(cfg, "head")
            
            logger.info("✅ Fresh migration setup complete")
            return True
            
        except Exception as e:
            logger.error(f"❌ Failed to create fresh migration: {e}")
            return False
    
    def validate_migrations(self) -> Dict[str, Any]:
        """Validate migration consistency."""
        validation_result = {
            "valid": True,
            "errors": [],
            "warnings": [],
            "migration_count": 0,
            "current_revision": None,
        }
        
        try:
            # Check current revision
            current_rev = self.get_current_revision()
            validation_result["current_revision"] = current_rev
            
            # Check for pending migrations
            pending = self.check_for_pending_migrations()
            if pending:
                validation_result["warnings"].append(
                    f"Pending migrations found: {pending}"
                )
            
            # Count migrations
            if self.versions_dir.exists():
                validation_result["migration_count"] = len(
                    list(self.versions_dir.glob("*.py"))
                )
            
            # Check if database is in sync
            cfg = self.get_alembic_config()
            from alembic.script import ScriptDirectory
            script_dir = ScriptDirectory.from_config(cfg)
            
            if current_rev:
                try:
                    script_dir.get_revision(current_rev)
                except Exception:
                    validation_result["valid"] = False
                    validation_result["errors"].append(
                        f"Current revision {current_rev} not found in migrations"
                    )
            
        except Exception as e:
            validation_result["valid"] = False
            validation_result["errors"].append(f"Validation error: {e}")
            
        return validation_result
    
    def auto_upgrade(self) -> bool:
        """Automatically upgrade to latest migrations."""
        try:
            # Check if there are pending migrations
            pending = self.check_for_pending_migrations()
            
            if not pending:
                logger.info("✅ No pending migrations")
                return True
            
            logger.info(f"🔄 Applying {len(pending)} pending migrations...")
            return self.run_migrations("head")
            
        except Exception as e:
            logger.error(f"❌ Auto upgrade failed: {e}")
            return False


# Global instance
alembic_manager = AlembicManager()


def get_alembic_manager() -> AlembicManager:
    """Get the global Alembic manager instance."""
    return alembic_manager


def check_migrations_on_startup() -> bool:
    """Check migrations on application startup."""
    try:
        logger.info("🔍 Checking database migrations...")
        
        # Validate migrations
        validation = alembic_manager.validate_migrations()
        
        if not validation["valid"]:
            logger.error("❌ Migration validation failed:")
            for error in validation["errors"]:
                logger.error(f"  - {error}")
            return False
        
        # Check for pending migrations
        pending = alembic_manager.check_for_pending_migrations()
        if pending:
            logger.warning(f"⚠️ Found {len(pending)} pending migrations")
            
            # Auto-apply if configured
            if getattr(settings, 'auto_apply_migrations', False):
                logger.info("🔄 Auto-applying migrations...")
                return alembic_manager.auto_upgrade()
            else:
                logger.info("💡 Run migrations manually: alembic upgrade head")
        else:
            logger.info("✅ Database is up to date")
            
        return True
        
    except Exception as e:
        logger.error(f"❌ Migration check failed: {e}")
        return False 